hook to install ffmpeg

diff --git a/charts/nextcloud/1.6.16/templates/deployment.yaml b/charts/nextcloud/1.6.16/templates/deployment.yaml
--- a/charts/nextcloud/1.6.16/templates/deployment.yaml
+++ b/charts/nextcloud/1.6.16/templates/deployment.yaml
@@ -82,6 +82,18 @@ spec: {{ include "common.deployment.common_spec" . | nindent 2 }}
         - name: extrappvolume-{{ $index }}
           mountPath: {{ $hostPathConfiguration.mountPath }}
         {{ end }}
+        lifecycle:
+          postStart:
+            exec:
+              command:
+                - /bin/sh
+                - -c
+                - |
+                  echo "Installing ffmpeg..."
+                  apt update && \
+                  apt install -y --no-install-recommends \
+                  ffmpeg || echo "Failed to install ffmpeg"
+                  echo "Finished."
 {{ include "common.networking.dnsConfiguration" .Values | nindent 6 }}
       volumes:
         - name: nginx-configuration
