fix value fetching

diff --git a/library/ix-dev/charts/nextcloud/templates/backup-postgres-config.yaml b/library/ix-dev/charts/nextcloud/templates/backup-postgres-config.yaml
--- a/library/ix-dev/charts/nextcloud/templates/backup-postgres-config.yaml
+++ b/library/ix-dev/charts/nextcloud/templates/backup-postgres-config.yaml
@@ -8,11 +8,17 @@ data:
   entrypoint.sh: |-
     #!/bin/bash
     echo "Fetching password from config.php"
-    # sed removes ' and , and => and dbpassword and spaces'
+
+    # sed removes ' , => spaces and db* from the string
+    DBUSER=$(cat /nc-config/config.php | grep "dbuser" | sed "s/dbuser\| \|'\|,\|=>//g")
     DBPASS=$(cat /nc-config/config.php | grep "dbpassword" | sed "s/dbpassword\| \|'\|,\|=>//g")
+    DBNAME=$(cat /nc-config/config.php | grep "dbname" | sed "s/dbname\| \|'\|,\|=>//g")
+    [ -n "$DBUSER" ] && [ -n "$DBPASS" ] && [ -n "$DBNAME" ] && echo "User, Database and password fetched from config.php"
 
     until pg_isready -U ${POSTGRES_USER} -h ${POSTGRES_HOST}; do sleep 2; done
 
-    # pg_dump will use the password from the PGPASSWORD environment variable
-    echo "Creating backup of ${POSTGRES_DB} database"
-    PGPASSWORD=${DBPASS} pg_dump -U $POSTGRES_USER -d ${POSTGRES_DB} --host=${POSTGRES_HOST} > /postgres_backups/$BACKUP_NAME;
+    # pg_dump will automatically use the password from the PGPASSWORD environment variable
+    echo "Creating backup of ${DBNAME} database as ${DBUSER}"
+    PGPASSWORD=${DBPASS} pg_dump -U $DBUSER -d $DBNAME --host=${POSTGRES_HOST} > /postgres_backups/$BACKUP_NAME \
+      && echo "Backup created successfully" \
+      || echo "Backup failed"
